package com.architecture.memory.orkestify.service.llm;

import com.architecture.memory.orkestify.dto.github.ImpactReport;
import com.architecture.memory.orkestify.model.LlmConfiguration;
import com.architecture.memory.orkestify.repository.LlmConfigurationRepository;
import com.fasterxml.jackson.databind.ObjectMapper;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;

/**
 * Generates PR analysis reports using LLM
 */
@Service
@RequiredArgsConstructor
@Slf4j
public class LlmReportGenerator {

    private final LlmService llmService;
    private final LlmConfigurationRepository llmConfigRepository;
    private final ObjectMapper objectMapper = new ObjectMapper();

    private static final String FEATURE_PR_ANALYSIS = "PR_ANALYSIS";

    /**
     * Generate PR analysis report using LLM
     */
    public String generatePrAnalysisReport(ImpactReport report) {
        log.info("Generating LLM-based PR analysis report for PR #{}", report.getPrNumber());

        // Get LLM configuration for PR analysis
        LlmConfiguration config = llmConfigRepository
                .findByFeatureAndActiveTrue(FEATURE_PR_ANALYSIS)
                .orElseThrow(() -> new RuntimeException(
                        "No active LLM configuration found for feature: " + FEATURE_PR_ANALYSIS));

        // Build system prompt
        String systemPrompt = buildSystemPrompt();

        // Build user prompt with impact data
        String userPrompt = buildUserPrompt(report);

        // Generate report using LLM
        String llmReport = llmService.generate(config, systemPrompt, userPrompt);

        // Wrap with HTML comment marker for updates
        return "<!-- orkestify-impact-report -->\n" + llmReport;
    }

    /**
     * Build comprehensive system prompt for PR analysis
     */
    private String buildSystemPrompt() {
        return """
                You are an expert software architect and code reviewer analyzing pull request changes.

                Your task is to generate a comprehensive, actionable PR analysis report in GitHub-flavored Markdown.

                ## Report Structure (MUST follow exactly):

                ## 🏗️ Architecture Impact Report

                ## 🎯 Risk Assessment

                **Overall Risk: [LOW/MEDIUM/HIGH/CRITICAL]** [emoji]
                **Risk Score: X/100**

                ### Score Breakdown
                - 🔴 Breaking Changes: X/40 (explanation if >20)
                - 🟡 Downstream Impact: X/30 (explanation if >15)
                - 🟢 Service Criticality: X/20 (explanation if >10)
                - 🟢 Change Complexity: X/10 (explanation if >5)

                ---

                ### ⚠️ Key Risk Factors

                **HIGH SEVERITY** (if any)
                - [Factor description]

                **MEDIUM SEVERITY** (if any)
                - [Factor description]

                **LOW SEVERITY** (if any)
                - [Factor description]

                ---

                ### ✅ Recommended Actions

                **Before Merging:**
                - [ ] [Action item]

                **Deployment Strategy:**
                - [Deployment recommendation]
                - Feature flag: [Required/Not required]
                - Reasoning: [Why this strategy]

                **Merge Status:** [Status with emoji]
                ---

                ### Summary

                [Table with metrics]

                ### [Additional sections as needed for API changes, circular dependencies, etc.]

                ---
                *Generated by Orkestify AI*

                ## Scoring Guidelines:

                **Breaking Changes (0-40):**
                - API URL changes: 25-35 points (based on severity)
                - Controller modifications: 10 points each
                - Circular dependencies: 10-15 points

                **Downstream Impact (0-30):**
                - Per consumer affected: 5 points (up to 20)
                - Affected endpoints: 3 points each (up to 15)
                - Affected flows: 2 points each (up to 10)

                **Service Criticality (0-20):**
                - Core services (Service/Repository): 4 points each (up to 12)
                - Kafka listeners: 8 points each (up to 8)

                **Change Complexity (0-10):**
                - Components changed: 0.5 points each (up to 5)
                - Lines changed >500: 5 points, >250: 3 points, >100: 2 points

                **Risk Levels:**
                - CRITICAL: 70+ points
                - HIGH: 50-69 points
                - MEDIUM: 25-49 points
                - LOW: 0-24 points

                ## Style Guidelines:

                1. **Be concise and actionable** - Developers need quick, clear guidance
                2. **Use emojis sparingly** - Only for risk levels and critical warnings
                3. **Highlight critical issues** - Use bold and warnings for breaking changes
                4. **Provide specific recommendations** - Say exactly what to do, not just what's wrong
                5. **Include WHO/WHAT/HOW** for API changes:
                   - WHO: List affected consumers
                   - WHAT: Describe what will break
                   - HOW: Provide 2-3 fix options
                6. **Calculate scores accurately** - Follow the scoring guidelines precisely
                7. **Be realistic** - If no consumers found, acknowledge uncertainty
                8. **Format tables properly** - Use GitHub-flavored Markdown tables

                ## Critical Rules:

                1. If API URLs changed and consumers detected → Score 60+ (HIGH/CRITICAL)
                2. If API URLs changed but no consumers → Score 30-40 (MEDIUM), note uncertainty
                3. If circular dependencies introduced → Add 10-15 to breaking changes
                4. Always show graph diff inconsistencies if relationships broken
                5. Block merge (🚨 BLOCKED status) for:
                   - Circular dependency errors
                   - API URL changes with consumers
                6. Never say "Ready to merge" for HIGH/CRITICAL risk

                Generate a professional, actionable report following this structure exactly.
                """;
    }

    /**
     * Build user prompt with impact analysis data
     */
    private String buildUserPrompt(ImpactReport report) {
        try {
            StringBuilder prompt = new StringBuilder();

            prompt.append("Analyze this pull request and generate a comprehensive risk assessment report.\n\n");

            prompt.append("## PR Information\n");
            prompt.append("- PR Number: #").append(report.getPrNumber()).append("\n");
            prompt.append("- Branch: ").append(report.getBranchName()).append("\n");
            if (report.getPrUrl() != null) {
                prompt.append("- URL: ").append(report.getPrUrl()).append("\n");
            }
            prompt.append("\n");

            prompt.append("## Impact Analysis Data\n\n");

            // Changed Components
            if (!report.getChangedComponents().isEmpty()) {
                prompt.append("### Changed Components (").append(report.getChangedComponents().size()).append(")\n");
                for (ImpactReport.ChangedComponent comp : report.getChangedComponents()) {
                    prompt.append("- **").append(comp.getType()).append("**: `").append(comp.getClassName()).append("`\n");
                    prompt.append("  - Status: ").append(comp.getFileStatus()).append("\n");
                    prompt.append("  - Changes: +").append(comp.getLinesAdded())
                            .append(" -").append(comp.getLinesRemoved()).append("\n");
                    if (!comp.getUpstreamCallers().isEmpty()) {
                        prompt.append("  - Called by: ").append(String.join(", ", comp.getUpstreamCallers())).append("\n");
                    }
                    if (!comp.getDownstreamCallees().isEmpty()) {
                        prompt.append("  - Calls: ").append(String.join(", ", comp.getDownstreamCallees())).append("\n");
                    }
                }
                prompt.append("\n");
            }

            // API URL Changes (CRITICAL)
            if (!report.getApiUrlChangeDetails().isEmpty()) {
                prompt.append("### 🚨 API URL Changes (CRITICAL)\n");
                for (ImpactReport.ApiUrlChangeDetail detail : report.getApiUrlChangeDetails()) {
                    prompt.append("- **Class**: `").append(detail.getClassName()).append("`\n");
                    prompt.append("  - Old URL: `").append(detail.getOldUrl()).append("`\n");
                    prompt.append("  - New URL: `").append(detail.getNewUrl()).append("`\n");
                    prompt.append("  - Change Type: ").append(detail.getChangeType()).append("\n");
                    prompt.append("  - Breaking Points: ").append(detail.getBreakingChangesPoints()).append("/40\n");

                    if (detail.getConsumers() != null && !detail.getConsumers().isEmpty()) {
                        prompt.append("  - **Consumers (").append(detail.getConsumers().size()).append(")**: ")
                                .append(String.join(", ", detail.getConsumers())).append("\n");
                    } else {
                        prompt.append("  - **Consumers**: None detected (dead code or external)\n");
                    }
                }
                prompt.append("\n");
            }

            // Affected Endpoints
            if (!report.getAffectedEndpoints().isEmpty()) {
                prompt.append("### Affected Endpoints (").append(report.getAffectedEndpoints().size()).append(")\n");
                for (ImpactReport.AffectedEndpoint ep : report.getAffectedEndpoints()) {
                    prompt.append("- `").append(ep.getHttpMethod()).append(" ").append(ep.getPath()).append("`\n");
                    prompt.append("  - Controller: ").append(ep.getControllerClass()).append("\n");
                    prompt.append("  - Reason: ").append(ep.getReason()).append("\n");
                }
                prompt.append("\n");
            }

            // Affected Flows
            if (!report.getAffectedFlows().isEmpty()) {
                prompt.append("### Affected Request Flows (").append(report.getAffectedFlows().size()).append(")\n");
                for (ImpactReport.AffectedFlow flow : report.getAffectedFlows()) {
                    prompt.append("- ").append(flow.getEndpoint()).append("\n");
                    prompt.append("  - Chain: ").append(String.join(" → ", flow.getCallChain())).append("\n");
                    prompt.append("  - Affected at: ").append(flow.getAffectedAt()).append("\n");
                }
                prompt.append("\n");
            }

            // Circular Dependencies
            if (!report.getNewCircularDependencies().isEmpty()) {
                prompt.append("### 🔴 New Circular Dependencies (").append(report.getNewCircularDependencies().size()).append(")\n");
                for (var dep : report.getNewCircularDependencies()) {
                    prompt.append("- **").append(dep.getSeverity()).append("**: ").append(dep.getDescription()).append("\n");
                    prompt.append("  - Cycle: ").append(String.join(" → ", dep.getCycle())).append("\n");
                }
                prompt.append("\n");
            }

            // Graph Diff Summary
            if (report.getDiffSummary() != null) {
                var diff = report.getDiffSummary();
                prompt.append("### Graph Diff Summary\n");
                prompt.append("- Nodes added: ").append(diff.getNodesAdded()).append("\n");
                prompt.append("- Nodes modified: ").append(diff.getNodesModified()).append("\n");
                prompt.append("- Nodes removed: ").append(diff.getNodesRemoved()).append("\n");
                prompt.append("- Relationships added: ").append(diff.getRelationshipsAdded()).append("\n");
                prompt.append("- Relationships removed: ").append(diff.getRelationshipsRemoved()).append("\n");
                prompt.append("\n");
            }

            // Warnings
            if (!report.getWarnings().isEmpty()) {
                prompt.append("### Warnings\n");
                for (String warning : report.getWarnings()) {
                    prompt.append("- ").append(warning).append("\n");
                }
                prompt.append("\n");
            }

            prompt.append("\n**Generate the complete PR analysis report following the structure exactly.**");

            return prompt.toString();

        } catch (Exception e) {
            log.error("Error building user prompt: {}", e.getMessage(), e);
            throw new RuntimeException("Failed to build prompt", e);
        }
    }
}
