package com.architecture.memory.orkestify.dto.rag;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.ArrayList;
import java.util.List;

/**
 * Response from Graph RAG query containing the LLM answer
 * and references to the graph nodes used for context.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class GraphRagAnswer {

    /**
     * Natural language answer generated by the LLM
     */
    @Builder.Default
    private String answer = "";

    /**
     * List of Neo4j node IDs that were used as context for the answer
     */
    @Builder.Default
    private List<String> nodeIds = new ArrayList<>();

    /**
     * List of matched code chunks with similarity scores
     */
    @Builder.Default
    private List<MatchedChunk> matchedChunks = new ArrayList<>();

    /**
     * Number of results retrieved from Qdrant
     */
    private int resultCount;

    /**
     * Processing time in milliseconds
     */
    private long processingTimeMs;

    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class MatchedChunk {
        private String nodeId;
        private String nodeType;
        private String className;
        private String methodName;
        private String signature;
        private double score;
        private String context;
    }
}
